//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Interpol.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InterpolEntities : DbContext
    {
        public InterpolEntities()
            : base("name=InterpolEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Dela> Delas { get; set; }
        public virtual DbSet<Lica_v_baze> Lica_v_baze { get; set; }
        public virtual DbSet<Message> Messages { get; set; }
        public virtual DbSet<Nation> Nations { get; set; }
        public virtual DbSet<Prest_prof> Prest_prof { get; set; }
        public virtual DbSet<Prestupniki> Prestupnikis { get; set; }
        public virtual DbSet<Prichiny_vyb> Prichiny_vyb { get; set; }
        public virtual DbSet<Razyskivaemye> Razyskivaemyes { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Sledovateli> Sledovatelis { get; set; }
        public virtual DbSet<Statiyi> Statiyis { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Stepeni_st> Stepeni_st { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Tip_prest> Tip_prest { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Vybyvshie> Vybyvshies { get; set; }
        public virtual DbSet<Zvaniya> Zvaniyas { get; set; }
    }
}
