//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Interpol.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int Id_Message { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public string Text { get; set; }
        public byte[] Image { get; set; }
        public Nullable<int> Kod_lica { get; set; }
    
        public virtual Lica_v_baze Lica_v_baze { get; set; }
    }
}
