//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Interpol.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prestupniki
    {
        public int Kod { get; set; }
        public Nullable<int> Tip { get; set; }
        public Nullable<int> Professiya { get; set; }
        public Nullable<int> Statiya { get; set; }
        public Nullable<System.DateTime> Data_zakl { get; set; }
        public Nullable<System.DateTime> Data_osv { get; set; }
    
        public virtual Lica_v_baze Lica_v_baze { get; set; }
        public virtual Prest_prof Prest_prof { get; set; }
        public virtual Tip_prest Tip_prest { get; set; }
    }
}
