//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Interpol.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Razyskivaemye
    {
        public int Kod { get; set; }
        public Nullable<int> Kod_dela { get; set; }
        public Nullable<System.DateTime> Data_prop { get; set; }
        public string Pred_mesto { get; set; }
    
        public virtual Dela Dela { get; set; }
        public virtual Lica_v_baze Lica_v_baze { get; set; }
    }
}
