//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Interpol.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sledovateli
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sledovateli()
        {
            this.Delas = new HashSet<Dela>();
        }
    
        public int Kod { get; set; }
        public string F { get; set; }
        public string I { get; set; }
        public string O { get; set; }
        public string Pol { get; set; }
        public Nullable<System.DateTime> Data_Rozhd { get; set; }
        public string Zvanie { get; set; }
        public Nullable<int> Stazh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dela> Delas { get; set; }
        public virtual Zvaniya Zvaniya { get; set; }
    }
}
